[profile.default]
solc= '0.8.20'
src = "src"
out = "out"
libs = ["node_modules", "lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config